name: Enumerate Azure Storage

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  enumerate:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: 22225454-dda2-4892-b644-e0d7d76f96ca
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: 5ff86dd0-ee91-4f26-901a-158f9242c514

      - name: Enumerar todo el storage
        run: |
          SA="iamazurelab325a466ba"

          echo "=== CONTENEDORES ==="
          az storage container list \
            --account-name $SA \
            --auth-mode login \
            --query '[].{nombre:name}' \
            -o tsv

          echo "=== BLOBS POR CONTENEDOR ==="
          for CONT in $(az storage container list \
            --account-name $SA \
            --auth-mode login \
            --query '[].name' \
            -o tsv); do
            echo "--- Contenedor: $CONT ---"
            az storage blob list \
              --container-name $CONT \
              --account-name $SA \
              --auth-mode login \
              --query '[].name' \
              -o tsv
          done
